---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

  # TODO: validate the permission to queues overlaps with defined queues/topics


# Configure technical user
- name: Prepare user account
  user:
    name: activemq
    system: true
    home: /opt/activemq/
    create_home: true

# Install
- name: Install base packages
  package:
    name: "{{item}}"
  with_items: "{{install_packages}}"

- name: Get stat information about /opt/activemq/current
  stat:
    path: /opt/activemq/current
  register: stat_current

# - name: Download installer from Internet
#   get_url:
#     url: https://archive.apache.org/dist/activemq/{{activemq_version}}/apache-activemq-{{activemq_version}}-bin.tar.gz
#     dest: apache-activemq-{{activemq_version}}-bin.tar.gz
#     mode: 0755
#   delegate_to: localhost
#   when: local_download
#
# - name: Create /opt/activemq/apache-activemq-{{activemq_version}} folder
#   file:
#     path: /opt/activemq/apache-activemq-{{activemq_version}}
#     state: directory
#   when: local_download
#
# - name: Install from source codes
#   unarchive:
#     src: apache-activemq-{{activemq_version}}-bin.tar.gz
#     dest: /opt/activemq/
#     remote_src: true
#     owner: activemq
#     group: activemq
#   when: local_download

- name: Install from source codes
  unarchive:
    src: https://archive.apache.org/dist/activemq/{{activemq_version}}/apache-activemq-{{activemq_version}}-bin.tar.gz
    dest: /opt/activemq/
    remote_src: true
    owner: activemq
    group: activemq
  when:
    - not local_download
    - not stat_current.stat.exists or
      (stat_current.stat.exists and not stat_current.stat.lnk_target is search("activemq-"+activemq_version))

- name: Activate current version
  file:
    src: "/opt/activemq/apache-activemq-{{activemq_version}}"
    dest: /opt/activemq/current
    owner: activemq
    group: activemq
    state: link

# Configure SystemD service
- name: Systemd service
  template:
    src: activemq.service.j2
    dest: /etc/systemd/system/activemq.service

- name: Systemd enable service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: activemq.service

# JMX
- name: ensure password files for jmx are not publicky readable
  file:
    path: "{{item}}"
    mode: 0600
    owner: activemq
    group: activemq
  loop:
    - /opt/activemq/current/conf/jmx.access

- name: configure jmx passwords
  template:
    src: jmx.password.j2
    dest: /opt/activemq/current/conf/jmx.password
    mode: 0600
    owner: activemq
    group: activemq

- name: configure jetty passwords
  template:
    src: jetty-realm.properties.j2
    dest: /opt/activemq/current/conf/jetty-realm.properties
    mode: 0644
    owner: activemq
    group: activemq
  notify: restart activemq

# Prepare SSL keystore
- name: Prepare java keystore passphrase
  set_fact:
    activemq_ssl_jkspass: "{{ansible_date_time.iso8601_micro | to_uuid}}"
  when: activemq_ssl_key and activemq_ssl_certificate

- name: Build java keystore
  java_keystore:
    name: activemq
    certificate: "{{activemq_ssl_certificate}}"
    private_key: "{{activemq_ssl_key}}"
    password: "{{activemq_ssl_jkspass}}"
    dest: /opt/activemq/current/conf/keystore.jks
    owner: activemq
    group: activemq
    mode: 0650
    force: true
  notify: restart activemq
  when: activemq_ssl_key and activemq_ssl_certificate

# Configure ActiveMQ
- name: Merge transport_connector options
  set_fact:
    activemq_transport_connector: "{{activemq_transport_connector_default|combine_listmap(activemq_transport_connector)}}"

- name: Configure ActiveMQ (activemq.xml)
  template:
    src: activemq.xml.j2
    dest: /opt/activemq/current/conf/activemq.xml
    owner: activemq
    group: activemq
    mode: 0644
  notify: restart activemq
  tags: config

- name: Configure ActiveMQ (env)
  template:
    src: env.j2
    dest: /opt/activemq/current/bin/env
    owner: activemq
    group: activemq
    mode: 0644
  notify: restart activemq
  tags: config

- name: configure user passwords
  template:
    src: credentials.properties.j2
    dest: /opt/activemq/current/conf/credentials.properties
    mode: 0640
    owner: activemq
    group: activemq
  notify: restart activemq

- name: configure user properties
  template:
    src: users.properties.j2
    dest: /opt/activemq/current/conf/users.properties
    mode: 0640
    owner: activemq
    group: activemq
  notify: restart activemq
